// github.com/nasdevs

#include <iostream>
#include <windows.h>
#include <unistd.h>
using namespace std;

int main() {
	system("cls");
	cout << "                           0 HELIKOPTER      " << endl;
	cout << "                           A                 " << endl;
	cout << "                    ----------------         " << endl;
	cout << "    \\              /           ____ \\      " << endl;
	cout << "     \\\\============           |    | \\    " << endl;
	cout << "                   \\          [____]  \\    " << endl;
	cout << "                    \\                 /     " << endl;
	cout << "                     -----------------       " << endl;
	cout << "                         |       |           " << endl;
	cout << "                 -------------------/        " << endl;
	cout << "_____._____._____._____.i____._____.____" << endl;
	while(true) {
		Sleep(100);
		system("cls");
		cout << "                HELIKOPTER 0             " << endl;
		cout << "                           A             " << endl;
		cout << "                    ----------------     " << endl;
		cout << "    |              /           ____ \\   " << endl;
		cout << "    | \\============           |    | \\ " << endl;
		cout << "                   \\          [____]  \\" << endl;
		cout << "                    \\                 / " << endl;
		cout << "                     -----------------   " << endl;
		cout << "                         |       |       " << endl;
		cout << "                 -------------------/    " << endl;
		cout << "__._____._____._____._____._____._____._" << endl;
		Sleep(100);
		system("cls");
		cout << "                           0 HELIKOMPTER " << endl;
		cout << "                           A             " << endl;
		cout << "                    ----------------     " << endl;
		cout << "    /              /           ____ \\   " << endl;
		cout << "   /  \\============           |    | \\ " << endl;
		cout << "                   \\          [____]  \\" << endl;
		cout << "                    \\                 / " << endl;
		cout << "                     -----------------   " << endl;
		cout << "                         |       |       " << endl;
		cout << "                 -------------------/    " << endl;
		cout << "._____._____._____._____._____._____.___" << endl;
		Sleep(100);
		system("cls");
		cout << "                HELIKOPTER 0             " << endl;
		cout << "                           A             " << endl;
		cout << "                    ----------------     " << endl;
		cout << "   ___             /           ____ \\   " << endl;
		cout << "      \\============           |    | \\ " << endl;
		cout << "                   \\          [____]  \\" << endl;
		cout << "                    \\                 / " << endl;
		cout << "                     -----------------   " << endl;
		cout << "                         |       |       " << endl;
		cout << "                 -------------------/    " << endl;
		cout << "____._____._____._____._____._____._____" << endl;
		Sleep(100);
		system("cls");
		cout << "                           0 HELIKOPTER  " << endl;
		cout << "                           A             " << endl;
		cout << "                    ----------------     " << endl;
		cout << "    \\              /           ____ \\  " << endl;
		cout << "     \\\\============           |    | \\ " << endl;
		cout << "                   \\          [____]  \\" << endl;
		cout << "                    \\                 / " << endl;
		cout << "                     -----------------   " << endl;
		cout << "                         |       |       " << endl;
		cout << "                 -------------------/    " << endl;
		cout << "_._____._____._____._____._____._____.__" << endl;
		Sleep(100);
		system("cls");
		cout << "                HELIKOPTER 0             " << endl;
		cout << "                           A             " << endl;
		cout << "                    ----------------     " << endl;
		cout << "    |              /           ____ \\   " << endl;
		cout << "    | \\============           |    | \\ " << endl;
		cout << "                   \\          [____]  \\" << endl;
		cout << "                    \\                 / " << endl;
		cout << "                     -----------------   " << endl;
		cout << "                         |       |       " << endl;
		cout << "                 -------------------/    " << endl;
		cout << "___._____._____._____._____._____._____." << endl;
		Sleep(100);
		system("cls");
		cout << "                           0 HELIKOPTER  " << endl;
		cout << "                           A             " << endl;
		cout << "                    ----------------     " << endl;
		cout << "    /              /           ____ \\   " << endl;
		cout << "   /  \\============           |    | \\ " << endl;
		cout << "                   \\          [____]  \\" << endl;
		cout << "                    \\                 / " << endl;
		cout << "                     -----------------   " << endl;
		cout << "                         |       |       " << endl;
		cout << "                 -------------------/    " << endl;
		cout << "_._____._____._____._____._____._____.__" << endl;
		Sleep(100); 
		system("cls");
		cout << "                HELIKOPTER 0             " << endl;
		cout << "                           A             " << endl;
		cout << "                    ----------------     " << endl;
		cout << "   ___             /           ____ \\   " << endl;
		cout << "      \\============           |    | \\ " << endl;
		cout << "                   \\          [____]  \\" << endl;
		cout << "                    \\                 / " << endl;
		cout << "                     -----------------   " << endl;
		cout << "                         |       |       " << endl;
		cout << "                 -------------------/    " << endl;
		cout << "__._____._____._____._____._____._____._" << endl;
		Sleep(100);
		system("cls");
		cout << "                           0 HELIKOPTER  " << endl;
		cout << "                           A             " << endl;
		cout << "                    ----------------     " << endl;
		cout << "    \\              /           ____ \\  " << endl;
		cout << "     \\\\============           |    | \\ " << endl;
		cout << "                   \\          [____]  \\" << endl;
		cout << "                    \\                 / " << endl;
		cout << "                     -----------------   " << endl;
		cout << "                         |       |       " << endl;
		cout << "                 -------------------/    " << endl;
		cout << "._____._____._____._____._____._____.___" << endl;
	}
}
